apiVersion: v1
kind: ConfigMap
metadata:
  name: hostdevice-plugin-config
  namespace: kube-system
data:
  config.json: |
    {
      "socketPrefix": "hostdevice-plugin",
      "devices": {
        "addem.se/dev_yanzi_serial_radio": {
          "containerPath": "/dev/yanzi-serial-radio",
          "matchProperties": {
            "SUBSYSTEM": "tty",
            "ID_VENDOR": "Texas_Instruments",
            "ID_MODEL": "Yanzi_Serial_Radio"
          }
        },
        "addem.se/dev_deconz_conbee": {
          "containerPath": "/dev/deconz-conbee",
          "matchProperties": {
            "SUBSYSTEM": "tty",
            "ID_VENDOR": "FTDI",
            "ID_MODEL": "FT230X_Basic_UART"
          }
        }
      }
    }
