apiVersion: v1
kind: Pod
metadata:
  name: host-device-test
spec:
  restartPolicy: OnFailure
  containers:
  - image: alpine
    name: host-device-test-ctr
    resources:
      limits:
        github.com/everpeace-random: 10
    command:
    - sh
    - -c
    - |
      od -vAn -N4 -tu4 < /dev/everpeace-random
      sleep 1000000
